#!/bin/sh
#
# $FreeBSD: ports/local/mysqmail/files/mysqmail-dovecot-logger.in$
#
# PROVIDE: mysqmail-dovecot-logger
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable mysqmail-dovecot-logger
#
# mysqmail_dovecot_logger_enable="YES"
#
# See perdition(8) for flags
#

mysqmail_dovecot_logger_enable=${mysqmail_dovecot_logger_enable-"NO"}

. /etc/rc.subr

name="mysqmail_dovecot_logger"
rcvar=`set_rcvar`
required_files=/usr/local/etc/mysqmail.conf

command="/usr/local/sbin/mysqmail-dovecot-logger"
pidfile="/var/run/mysqmail-dovecot-logger.pid"

load_rc_config $name

run_rc_command "$1"
