.TH mysqmail-pure-ftpd-logger 8
.SH NAME
mysqmail-pure-ftpd-logger \- logs pureftpd traffic to a mysql database
.SH SYNOPSIS
.B mysqmail-pure-ftpd-logger
.I subprogram
[
.I args ...
]
.SH DESCRIPTION
.B mysqmail-pure-ftpd-logger
reads standard input and for each lines,
does an action in a selected table in the
selected mysql server (configuration done
using /etc/mysqmail.conf).

.B mysqmail-pure-ftpd-logger
uses a table corresponding to this one:

todo...

.SH "VERSION"
This documentation describes
.B mysqmail-pure-ftpd-logger
version 0.3.0-R0.
See
.B http://gplhost.com/?rub=softwares
for updates.
